config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions

  root  'static_pages#home'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get' 

end

app/models/user.rb
class User < ActiveRecord::Base
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  	def current_user
			@current_user ||= User.find(session[:user_id]) if session[:user_id]
  	end
  	helper_method :current_user

  	def authorize
			redirect_to login_url, alert: "Not authorized" if current_user.nil?
  	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
		user = User.find_by_email(params[:session][:email])
		if user && user.authenticate(params[:session][:password])
			session[:user_id] = user.id
			redirect_to root_path, notice: "Signed in!"
		else
			flash.now.alert = "Email or password is invalid"
			render 'new'
		end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_path, notice: "Signed out!"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def contact
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to root_path, notice: "Thank you for signing up!"
		else
			render 'new'
		end
	end

	private

		def user_params
			params.require(:user).permit(:email, :password, :password_confirmation)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "LoL App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash_messages.html.erb
<div class="row">
  <% flash.each do |key, value| %>
    <div class="small-12 columns alert-box radius <%= key %>"><%= value %></div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="row">
  <ul class="inline-list small-12 small-centered medium-12 medium-centered columns">
    <li><small>by Morgan VanDerLeest</small></li>
    <div class="inline-list right">
      <li><small><%= link_to "About",   '#' %></small></li>
      <li><small><%= link_to "Contact", '#' %></small></li>
      <li><small><%= link_to "Help",    '#' %></small></li>
    </div>
  </ul>
</footer>

app/views/layouts/_header.html.erb
<div class="contain-to-grid">
  <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name">
        <h1><%= link_to "LoL App", root_path %></h1>
      </li>
      <li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
    </ul>
    <section class="top-bar-section">
      <!-- Right Nav Section -->
      <ul class="right">
        <% if current_user %>
          <li><%= link_to "Profile", '#' %></li>
          <li><%= link_to "Settings", '#' %></li>
          <li><%= link_to "Sign out", signout_path, method: :delete %></li>
          </li>
        <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
        <% end %>
      </ul>
    </section>
  </nav>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= full_title(yield(:title)) %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/flash_messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
    
    <script>
      $(document).foundation();
    </script>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert-box alert radius">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<div class="row">
	<div class="small-10 small-centered text-center columns">
		<h1>About</h1>
	</div>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<div class="row">
	<div class="small-10 small-centered text-center columns">
		<h1>Contact</h1>
	</div>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<div class="row">
	<div class="small-10 small-centered text-center columns">
		<h1>Help</h1>
	</div>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, 'Lobby') if current_user %>
<div class="cover-box">
	<div class="row">
		<div class="small-6 small-centered text-center columns">
			<h2 class="quote-intro">Extend your senses</h2>
			<% if current_user %>
				Lorem ipsum
			<% else %>
				<%= link_to 'Sign up', signup_path, class: "button expand radius" %>
				<%= link_to 'Sign in', signin_path, class: "button expand radius" %>
			<% end %>
		</div>
	</div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1 class="text-center">Sign up</h1>
<div class="row">
  <div class="small-offset-3 small-6 columns">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>

    <%= f.text_field :email, placeholder: "Email" %>
    <%= f.password_field :password, placeholder: "Password" %>
    <%= f.password_field :password_confirmation, placeholder: "Password confirmation" %>

      <%= f.submit "Create my account", class: "button expand radius" %>
    <% end %>

    <p>Already have an account? <%= link_to "Log in", signin_path %></p>
  </div>
</div>